global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - 'localhost:8000'  # If you're running FastAPI natively
          - 'api:8000'        # If you're running it as a Docker container


